### ISSUE TITLE
Avoid errors from Google Closure Compiler

### ISSUE THREAD

**Issue by mairatma** [metal/metal-soy-bundle#1]
Google Closure Compiler is complaining quite a bit with our soy bundle and compiled soy files. The errors are related to:

1. `@define` must happen in the global space and cannot be wrapped in an amd call as we have for the `amd` and `amd-jquery` builds
2. `required "soy.asserts" namespace never provided`
3. `required "goog.i18n.bidi" namespace never provided`

**Comment by mairatma** [comment]
Number (1) was done here: https://github.com/metal/metal-soy-bundle/commits/master

**Comment by mairatma** [comment]
Hey @jbalsas, do the errors **1** and **2** happen when running closure compiler or are they actually runtime errors?

**Comment by jbalsas** [comment]
Hey Maíra! 

The errors are showing in our server logs, not in the browser console if that's what you were asking. They happen when we try to use Google Closure Compiler as minifier. You can see the compile configuration here:

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/minifier/GoogleJavaScriptMinifier.java

**Comment by mairatma** [comment]
Do you know if it's checking each file separately or something like that? Cause we do provide both these namespaces in the soy bundle, but maybe that file would need to be analyzed before the compiled soy ones?

I'm not sure why the compiler wouldn't notice that these are being provided, but from what I saw there are options you can set for the compiler to skip these errors at least, since they're wrong, like **jscomp_off**  and **hide_warnings_for**. You could also try turning off **process_closure_primitives**.

Either way I don't see how we could do something on our side to avoid this, seems like a problem with the compiler :(

**Comment by mairatma** [comment]
Just FYI, @jbalsas confirmed that this isn't a problem on the code. Actually we've decided to revert the change that removed the @define calls, keeping the source the same. Posting the conversation here:

<img width="955" alt="screen shot 2016-05-12 at 10 37 12 am" src="https://cloud.githubusercontent.com/assets/5216049/15216538/dc045682-182d-11e6-81ba-b815e5a6f1f7.png">
